#!/usr/bin/env python3

import sys
import argparse
import lib.utils as utils

from pathlib import Path


def parse_args():
    parser = argparse.ArgumentParser(
        description='remove duplicate reports')
    parser.add_argument('reports', metavar='DIR', type=Path,
                        help='reports directory')
    parser.add_argument('-o', '--output', metavar='DIR', type=Path,
                        default='unique-reports',
                        help='output to DIR (defualt: unique-reports)')
    parser.add_argument('-j', '--jobs', metavar='N', type=int, default=1,
                        help='run with N jobs (default: 1)')
    return parser.parse_args()


if __name__ == '__main__':
    args = parse_args()
    if not args.reports.exists():
        print(f'"{args.reports}" does not exist', file=sys.stderr)
        sys.exit(1)
    print('Parsing reports...')
    reports = utils.parse_reports(args.reports, args.jobs)
    print('Removing duplicate reports...')
    reports = utils.unique_reports(reports, utils.Policy.aggressive)
    print(f'Total of {len(reports)} unique report(s)')
    utils.copy_reports(reports, args.output)
    utils.generate_index(args.output)
